/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuhInvoice.sec;

import BuhInvoice.GP_BUH;
import BuhInvoice.HTMLPrint;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author KOCMOC
 */
public class ChooseStamp extends javax.swing.JFrame implements MouseListener {

    public static Boolean STAMP_CO2__NEUTRAL__MANUAL = false;
    public static Boolean STAMP_REVERSER_CHARGE_EU = false;
    public static Boolean STAMP_C = false;
    public static Boolean STAMP_D = false;

    private final ArrayList<JLabel> list_labels = new ArrayList<JLabel>();
    private Border INITIAL_LABEL_BORDER = null;
    private final Border LABEL_BORDER_ON_ENTER = BorderFactory.createRaisedBevelBorder();

    private HTMLPrint print;
    /**
     * Creates new form ChooseStamp
     */
    public ChooseStamp() {
        initComponents();
        init_a();
        init_b();
    }
    
    public ChooseStamp(HTMLPrint print) {
        initComponents();
        this.print = print;
        init_a();
        init_b();
    }

    private void init_a() {
        //
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //
        INITIAL_LABEL_BORDER = jLabel_stamp_1.getBorder();
        //
        list_labels.add(jLabel_stamp_1);
        list_labels.add(jLabel_stamp_2);
        list_labels.add(jLabel_stamp_3);
        list_labels.add(jLabel_stamp_4);
        //
    }

    private void init_b() {
        //
        for (JLabel label : list_labels) {
            //
            label.setOpaque(true); // Making the background white
            //
            label.addMouseListener(this);
            //
        }
        //
        //
        GP_BUH.setLabelIconAndToolTip(jLabel_stamp_1, "co2_free.png", 128, 75);
        GP_BUH.setLabelIconAndToolTip(jLabel_stamp_2, "reverse_charge.png", 128, 128);
        this.setSize(280, 320);
        //
        GP_BUH.centerAndBringToFront(this);
        //
    }

    private void resetStampsBools() {
        STAMP_CO2__NEUTRAL__MANUAL = false;
        STAMP_REVERSER_CHARGE_EU = false;
        STAMP_C = false;
        STAMP_D = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_stamp_1 = new javax.swing.JLabel();
        jLabel_stamp_2 = new javax.swing.JLabel();
        jLabel_stamp_3 = new javax.swing.JLabel();
        jLabel_stamp_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 2, 2));

        jLabel_stamp_1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_stamp_1);

        jLabel_stamp_2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_stamp_2);

        jLabel_stamp_3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_stamp_3);

        jLabel_stamp_4.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_stamp_4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseStamp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseStamp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseStamp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseStamp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChooseStamp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_stamp_1;
    private javax.swing.JLabel jLabel_stamp_2;
    private javax.swing.JLabel jLabel_stamp_3;
    private javax.swing.JLabel jLabel_stamp_4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {

    }

    @Override
    public void mousePressed(MouseEvent e) {
        //
        JLabel lbl = (JLabel) e.getSource();
        //
        resetStampsBools();
        //
        if (lbl.equals(jLabel_stamp_1)) {
            STAMP_CO2__NEUTRAL__MANUAL = true;
        } else if (lbl.equals(jLabel_stamp_2)) {
            STAMP_REVERSER_CHARGE_EU = true;
        } else if (lbl.equals(jLabel_stamp_3)) {
            STAMP_C = true;
        } else if (lbl.equals(jLabel_stamp_4)) {
            STAMP_D = true;
        }
        //
        this.setVisible(false);
        //
        print.go();
        //
    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {
        JLabel lbl = (JLabel) e.getSource();
        lbl.setBorder(LABEL_BORDER_ON_ENTER);
    }

    @Override
    public void mouseExited(MouseEvent e) {
        JLabel lbl = (JLabel) e.getSource();
        lbl.setBorder(INITIAL_LABEL_BORDER);
    }
}
