/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MCCompound;

import forall.GP;
import forall.HelpA;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import supplementary.HelpM;

/**
 *
 * @author KOCMOC
 */
public class ShowProgress extends javax.swing.JFrame implements Runnable {

    private boolean complete = false;
    private String completeMsg = "";

    /**
     * Creates new form ShowProgress
     */
    public ShowProgress() {
        initComponents();
        this.setTitle("Information");
        this.setIconImage(new ImageIcon(GP.IMAGE_ICON_URL).getImage());
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setAlwaysOnTop(true);
        setLocation(HelpA.position_window_in_center_of_the_screen(this));
    }

    public void setIconImage(URL url) {
        this.setIconImage(new ImageIcon(url).getImage());
    }

    public void goToEnd() {
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }

    public void enableHideOnClose() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

//    public void showMesasge(String currentOperation, String msg) {
//        setVisible(true);
//        jTextArea1.setText(currentOperation + "\n" + msg);
//    }

    public void showMessageAppend(String msg) {
        setVisible(true);
//        jTextArea1.append("\n" + currentOperation + "\n" + msg);
        jTextArea1.append("[" + HelpM.get_proper_date_and_time_default_format() + "]" + " -> " + msg + "\n");
    }

    public void setComplete(String msg) {
        this.completeMsg = msg;
        this.complete = true;
    }

    public void startCountDown() {
        Thread x = new Thread(this);
        x.start();
    }

    private String secondsToMiniutesAndSeconds(int seconds) {
        int sec = seconds % 60;
        int min = (seconds - sec) / 60;
        if (sec < 10) {
            return min + ":0" + sec;
        } else {
            return min + ":" + sec;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ShowProgress().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        int seconds = 180;
        String initial_title = getTitle();
        while (complete == false && seconds >= 0) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(ShowProgress.class.getName()).log(Level.SEVERE, null, ex);
            }
            //
            seconds--;
            //
            this.setTitle(initial_title + " " + secondsToMiniutesAndSeconds(seconds));
        }
        //
        setTitle(completeMsg);
        //
    }
}
