/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MCRecipe.Sec;
import MCRecipeLang.RECIPE_OVERVIEW_;
/**
 *
 * @author KOCMOC
 */
public class CustomPanelCp extends javax.swing.JPanel implements CustomPanelIF{

    /**
     * Creates new form CustomPanelCp
     */
    public CustomPanelCp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxRecipeInitial_Cost_from = new JComboBox_RI_C(BOX_PARAMS.COST_FROM,1);
        jComboBox_vk_preis_von = new JComboBox_RI_C(BOX_PARAMS.VK_PRICE_FROM,3);
        jComboBox_dichte_von = new JComboBox_RI_C(BOX_PARAMS.DICHTE_FROM,5);
        jComboBox_charge_von = new JComboBox_RI_C(BOX_PARAMS.CHARGE_FROM,7);
        jComboBoxRecipeInitial_Cost_to = new JComboBox_RI_C(BOX_PARAMS.COST_TO,2);
        jComboBox_vk_preis_bis = new JComboBox_RI_C(BOX_PARAMS.VK_PRICE_TO,4);
        jComboBox_dichte_bis = new JComboBox_RI_C(BOX_PARAMS.DICHTE_TO,6);
        jComboBox_charge_bis = new JComboBox_RI_C(BOX_PARAMS.CHARGE_TO,8);
        jComboBox_haltbarkeit_von = new JComboBox_RI_C(BOX_PARAMS.HALTBARKEIT_FROM,9);
        jComboBox_haltbarkeit_bis = new JComboBox_RI_C(BOX_PARAMS.HALTBARKEIT_TO,10);
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jComboBox_hardness_from = new JComboBox_RI_C(BOX_PARAMS.HARDNESS_FROM,11);
        jLabel67 = new javax.swing.JLabel();
        jComboBox_hardness_to = new JComboBox_RI_C(BOX_PARAMS.HARDNESS_TO,12);

        jComboBoxRecipeInitial_Cost_from.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_vk_preis_von.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_dichte_von.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_charge_von.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBoxRecipeInitial_Cost_to.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_vk_preis_bis.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_dichte_bis.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_charge_bis.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_haltbarkeit_von.setModel(new javax.swing.DefaultComboBoxModel());

        jComboBox_haltbarkeit_bis.setModel(new javax.swing.DefaultComboBoxModel());

        jLabel56.setText(RECIPE_OVERVIEW_.KOST_VON());

        jLabel57.setText(RECIPE_OVERVIEW_.VK_PREIS_VON());

        jLabel58.setText(RECIPE_OVERVIEW_.DICHTE_VON());

        jLabel59.setText(RECIPE_OVERVIEW_.CHARGE_KG_VON());

        jLabel60.setText(RECIPE_OVERVIEW_.KOST_BIS());

        jLabel61.setText(RECIPE_OVERVIEW_.VK_PREIS_BIS());

        jLabel62.setText(RECIPE_OVERVIEW_.DICHTE_BIS());

        jLabel63.setText(RECIPE_OVERVIEW_.CHARGE_KG_BIS());

        jLabel64.setText(RECIPE_OVERVIEW_.HALTBARKEIT_VON());

        jLabel65.setText(RECIPE_OVERVIEW_.HALTBARKEIT_BIS());

        jLabel66.setText(RECIPE_OVERVIEW_.HÄRTE_VON());

        jComboBox_hardness_from.setModel(new javax.swing.DefaultComboBoxModel());

        jLabel67.setText(RECIPE_OVERVIEW_.HÄRTE_BIS());

        jComboBox_hardness_to.setModel(new javax.swing.DefaultComboBoxModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRecipeInitial_Cost_from, 0, 111, Short.MAX_VALUE)
                            .addComponent(jLabel57)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxRecipeInitial_Cost_to, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60)
                            .addComponent(jLabel61))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel65)
                            .addComponent(jLabel64)
                            .addComponent(jComboBox_haltbarkeit_von, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox_vk_preis_von, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBox_vk_preis_bis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_dichte_von, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel58))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_dichte_bis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel62)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_charge_von, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel59))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel63)
                                    .addComponent(jComboBox_charge_bis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_hardness_to, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67)
                            .addComponent(jComboBox_hardness_from, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66)
                            .addComponent(jComboBox_haltbarkeit_bis, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(jLabel60)
                            .addComponent(jLabel64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxRecipeInitial_Cost_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxRecipeInitial_Cost_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_haltbarkeit_von, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel61)
                            .addComponent(jLabel65))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_vk_preis_von, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_vk_preis_bis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_haltbarkeit_bis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58)
                            .addComponent(jLabel62))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_dichte_von, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_dichte_bis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_hardness_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel59)
                            .addComponent(jLabel63))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_charge_von, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_charge_bis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_hardness_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox jComboBoxRecipeInitial_Cost_from;
    public javax.swing.JComboBox jComboBoxRecipeInitial_Cost_to;
    public javax.swing.JComboBox jComboBox_charge_bis;
    public javax.swing.JComboBox jComboBox_charge_von;
    public javax.swing.JComboBox jComboBox_dichte_bis;
    public javax.swing.JComboBox jComboBox_dichte_von;
    public javax.swing.JComboBox jComboBox_haltbarkeit_bis;
    public javax.swing.JComboBox jComboBox_haltbarkeit_von;
    public javax.swing.JComboBox jComboBox_hardness_from;
    public javax.swing.JComboBox jComboBox_hardness_to;
    public javax.swing.JComboBox jComboBox_vk_preis_bis;
    public javax.swing.JComboBox jComboBox_vk_preis_von;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    // End of variables declaration//GEN-END:variables
}
